name: Deploy Vite App

on:
  push:
    branches:
      - main  # Cambia 'main' si tu rama principal es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'  # Asegúrate de usar una versión compatible
      - run: npm install
      - run: npm run build
      - run: git add -A
      - run: git commit -m "Deploy to GitHub Pages"
      - run: git push origin gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
